### ISSUE TITLE
Tern completion doesn't work

### ISSUE THREAD

**Issue by xtal8** [maralla/completor.vim#31]
Hi,

I have node and NPM installed. I installed the plugin via `Vim-Plug` and ran `make js` in plugin's directory (didn't get any errors), but when I try to use it with .js files I only get buffer's keywords as completion. I tested it on Mint 17.3 and WSL. I also tried c++ completion which works fine.

Btw, thank you for the plugin.

**Comment by maralla** [comment]
#32 should fix the problem.

**Comment by xtal8** [comment]
I still can't get it to work. I tried to use `let g:completor_node_binary = '/usr/bin/node'` setting but it doesn't help. Is there any other setting I should try?

**Comment by maralla** [comment]
Upgrade completor.vim to the latest commit and run `make js` again. And use the following code as the *.tern-project* content:
```json
{
  "plugins": {
    "node": {},
    "es_modules": {}
  },
  "libs": [
    "ecma5",
    "ecma6"
  ],
  "ecmaVersion": 6
}
```

Then edit a js file *test.js*, enter the following code:
```js
a = [1, 2, 3]
a.
```
after entering `a.` the completion popup should be shown.

**Comment by xtal8** [comment]
I tried, but it doesn't work. I also tested on newly installed Ubuntu 16.04 it doesn't work there either. I only get buffer and path completion.

**Comment by maralla** [comment]
Go to `<root directory of completor.vim/pythonx/completers/javascript` and run `node tern_wrapper.js`. Is there any exceptions?

**Comment by xtal8** [comment]
I ran it and got the following: 
```
/home/m/.vim/plugged/completor.vim/pythonx/completers/javascript/tern_wrapper.js:67
      let def = readJson(found);
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```
I had node v4.2.6 installed. After that I installed v6.9.1, and now tern completions work as expected.
So the problem was my old version of node. Sorry for the noise and thank you for your patience and help.
