### ISSUE TITLE
Cursor jumps upward if escaping insert mode before buffer is populated.

### ISSUE THREAD

**Issue by dwayneyuen** [maralla/completor.vim#78]
The general issue appears to be if I type something and hit escape prior to the autocompletion buffer appearing, that my cursor jumps upwards. I have set `g:completor_auto_trigger` to  1.

I can replicate this specifically with the below example in python. 

If I have a module imported, and I type the module name, it tries to populate an autocompletion buffer with recommendations. Then when I type a period, it tries to populate an autocompletion buffer with recommendations from the module. But if I type the period before the first buffer appears, and then escape before the second buffer appears, then my cursor jumps up a seemingly arbitrary amount. I've been able to narrow this down to this plugin (all other plugins are disabled). This example triggers it for me:

```
import math

mat  # Finish typing 'math.' then hit esc
```

If you complete typing the word `math.` and escape before the autocompletion buffer pops up, your cursor should go up one line.

In some of my files my cursor will jump up ~20 lines with 100% reproducibility.

**Comment by cornop** [comment]
I can also reproduce this, it's quite annoying when completion is slow.

**Comment by maralla** [comment]
I committed a fix #97 for this problem. Please update and try again.

**Comment by cornop** [comment]
The problem is fixed for some cases, but it still persists, for example:

```
import numpy
numpy.
# make sure you have a line below
```

Adding anything on the `numpy.` line causes the cursor to move down. I picked `numpy` because its completion is slower than `math` and makes it easier to reproduce.

**Comment by dwayneyuen** [comment]
I experience the same behavior (cursor moving downward).

**Comment by maralla** [comment]
I pushed one more commit. Please update and try again.

**Comment by cornop** [comment]
The last commit fixed it for me. Thanks a lot!

**Comment by dwayneyuen** [comment]
The last commit fixed the previous upward jumping issue but I still have an issue with the cursor jumping a couple lines downward in the file that originally gave me this issue (but I can't share due to work). I'll try to create a minimal case that reproduces it.
