### ISSUE TITLE
rust integration issues

### ISSUE THREAD

**Issue by prairir** [maralla/completor.vim#87]
i setup completor and it work perfectly in everything except rust, when i try using rust with it i get an error
"Error detected while processing function <SNR>66_complete[7]..completor#do_complete[5]..completor#daemon#process[21]..267:
line 2:
E900: invalid job id"

i did all that the installation guide said, ie point it to my racer binary and install racer. racer works by itself in the command line ie typing in racer complete std::io:B and then getting a lot of output.

**Comment by maralla** [comment]
The fix #92 should resolve this problem.

**Comment by prairir** [comment]
i just updated and tried the fix and the problem is still happening.

**Comment by maralla** [comment]
I added one more commit #93. Could you please update and try it again?

**Comment by prairir** [comment]
it works perfectly now, thank you. :)
